#!/usr/bin/env bash
set -euo pipefail

VERSION_LABEL="${PMC8_BETA_VERSION:-PMC8-INDI-2.2.1-es1}"
SOURCE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_ROOT="${BUILD_ROOT:-"${SOURCE_ROOT}/build-pmc8-deb"}"
OUTPUT_DIR="${OUTPUT_DIR:-"${SOURCE_ROOT}/artifacts"}"
PACKAGE_BASENAME="pmc8-indi-debian"

usage() {
    cat <<USAGE
Usage: $0 [--build-root DIR] [--output-dir DIR]

Builds INDI-style Debian packages for the Explore Scientific PMC-Eight beta.

This script intentionally uses the repository's existing debian/ packaging,
builds in a temporary copy, and copies the generated .deb packages to
OUTPUT_DIR. Building on each target Ubuntu/Raspberry Pi OS release lets
dpkg-shlibdeps generate the correct runtime dependencies for that release
(for example libcfitsio9 on Ubuntu 22.04 or libcfitsio10t64 on Ubuntu 24.04).

Environment:
  PMC8_BETA_VERSION   Release label, default ${VERSION_LABEL}
  PMC8_DEB_VERSION    Debian package version override
  PMC8_DEB_DISTRO     Distro suffix/label override, default detected codename
  BUILD_ROOT          Temporary build root
  OUTPUT_DIR          Artifact output directory

USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --build-root)
            BUILD_ROOT="$2"
            shift 2
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

detect_codename() {
    if command -v lsb_release >/dev/null 2>&1; then
        lsb_release -cs
        return
    fi

    if [[ -r /etc/os-release ]]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        echo "${VERSION_CODENAME:-unknown}"
        return
    fi

    echo "unknown"
}

detect_arch() {
    if command -v dpkg >/dev/null 2>&1; then
        dpkg --print-architecture
        return
    fi

    uname -m
}

derive_deb_version() {
    local label="$1"
    local version
    version="${label#PMC8-INDI-}"
    version="${version//-es/+es}"
    echo "${version}"
}

DISTRO="${PMC8_DEB_DISTRO:-$(detect_codename)}"
ARCH="$(detect_arch)"
DEB_VERSION="${PMC8_DEB_VERSION:-$(derive_deb_version "${VERSION_LABEL}")}"
WORK_DIR="${BUILD_ROOT}/${PACKAGE_BASENAME}-${VERSION_LABEL}-${DISTRO}-${ARCH}"
SRC_COPY="${WORK_DIR}/source"

echo "Version label : ${VERSION_LABEL}"
echo "Deb version   : ${DEB_VERSION}"
echo "Distro        : ${DISTRO}"
echo "Architecture  : ${ARCH}"
echo "Build root    : ${WORK_DIR}"
echo "Output dir    : ${OUTPUT_DIR}"

command -v dpkg-buildpackage >/dev/null 2>&1 || {
    echo "dpkg-buildpackage is required. Install dpkg-dev/devscripts/debhelper first." >&2
    exit 1
}

rm -rf "${WORK_DIR}"
mkdir -p "${SRC_COPY}" "${OUTPUT_DIR}"

if command -v rsync >/dev/null 2>&1; then
    rsync -a \
        --exclude .git \
        --exclude build \
        --exclude build-pmc8-beta \
        --exclude build-pmc8-deb \
        --exclude artifacts \
        "${SOURCE_ROOT}/" "${SRC_COPY}/"
else
    tar -C "${SOURCE_ROOT}" \
        --exclude ./.git \
        --exclude ./build \
        --exclude ./build-pmc8-beta \
        --exclude ./build-pmc8-deb \
        --exclude ./artifacts \
        -cf - . | tar -C "${SRC_COPY}" -xf -
fi

tmp_changelog="${SRC_COPY}/debian/changelog.new"
{
    echo "libindi (${DEB_VERSION}) ${DISTRO}; urgency=medium"
    echo
    echo "  * Explore Scientific PMC-Eight beta package ${VERSION_LABEL}."
    echo "  * Built as INDI-style Debian packages for ${DISTRO}/${ARCH}."
    echo
    echo " -- Explore Scientific <support@explorescientific.com>  $(date -R)"
    echo
    cat "${SRC_COPY}/debian/changelog"
} > "${tmp_changelog}"
mv "${tmp_changelog}" "${SRC_COPY}/debian/changelog"

(
    cd "${SRC_COPY}"
    dpkg-buildpackage -b -us -uc -d
)

shopt -s nullglob
packages=("${WORK_DIR}"/*.deb "${WORK_DIR}"/*.changes "${WORK_DIR}"/*.buildinfo)
if [[ "${#packages[@]}" -eq 0 ]]; then
    echo "No Debian package outputs found in ${WORK_DIR}" >&2
    exit 1
fi

for pkg in "${packages[@]}"; do
    cp -a "${pkg}" "${OUTPUT_DIR}/"
done

(
    cd "${OUTPUT_DIR}"
    sha256sum ./*.deb > "SHA256SUMS-${VERSION_LABEL}-${DISTRO}-${ARCH}.txt"
)

cat > "${OUTPUT_DIR}/README-DEBIAN-${VERSION_LABEL}-${DISTRO}-${ARCH}.md" <<README
# Explore Scientific PMC-Eight INDI Debian Packages

Release label: ${VERSION_LABEL}
Debian package version: ${DEB_VERSION}
Target distribution: ${DISTRO}
Architecture: ${ARCH}

Install the runtime packages generated by this build:

\`\`\`bash
sudo apt update
sudo apt install ./libindi-data_${DEB_VERSION}_all.deb ./libindi1_${DEB_VERSION}_${ARCH}.deb ./indi-bin_${DEB_VERSION}_${ARCH}.deb
\`\`\`

The packages use normal Debian dependency metadata. If additional runtime
libraries are required on the target system, apt will report and install the
appropriate package for this OS release.

Verify:

\`\`\`bash
which indi_pmc8_telescope
ldd \$(which indi_pmc8_telescope)
indiserver -v indi_pmc8_telescope
\`\`\`

If you need to return to the distribution-provided INDI packages:

\`\`\`bash
sudo apt install --reinstall indi-bin libindi1 libindi-data
\`\`\`
README

echo "Generated Debian package artifacts:"
printf '  %s\n' "${packages[@]##*/}"
echo "Copied to ${OUTPUT_DIR}"
